// <auto-generated />
namespace IntegrationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class intergration_init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intergration_init));
        
        string IMigrationMetadata.Id
        {
            get { return "201610281043048_intergration_init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
