// <auto-generated />
namespace RetailEnterprise.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class retailer_to_enterprise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(retailer_to_enterprise));
        
        string IMigrationMetadata.Id
        {
            get { return "201610271426017_retailer_to_enterprise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
