// <auto-generated />
namespace RetailEnterprise.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class retail_enterprise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(retail_enterprise));
        
        string IMigrationMetadata.Id
        {
            get { return "201610271012413_retail_enterprise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
